<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <ApplicationIcon>sql.ico</ApplicationIcon>
        <TargetFramework>net9.0-windows</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
      <PackageReference Include="ClosedXML" Version="0.105.0" />
      <PackageReference Include="Extended.Wpf.Toolkit" Version="5.0.0" />
      <PackageReference Include="MaterialDesignThemes" Version="4.9.0" />
      <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.11">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="9.0.11" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.11" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.11">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="9.0.11" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
      <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.2" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="auth.json" />
      <None Remove="databin.json" />
      <Content Include="databin.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <None Remove="Assets\logo.png" />
      <Resource Include="Assets\logo.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <None Remove="Assets\add.png" />
      <Resource Include="Assets\add.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <None Remove="Assets\choose.png" />
      <Resource Include="Assets\choose.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
    </ItemGroup>

    <ItemGroup>
      <Page Update="Views\DatabaseConfigView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Views\LoginView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Views\CreateOptionView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Views\EditOptionView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Views\ExportView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Views\LevelView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Views\MainMenuView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Views\MainWindow.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Views\QueryView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Views\SaveView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Views\SettingsView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
    </ItemGroup>

</Project>
